spring:
  application:
    name: order-service
  jpa:
    hibernate:
      ddl-auto: update
management:
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
    jmx:
      exposure:
        include: '*'
server:
  port : 8012

catalogue:
  resource:
    host: ${CATALOGUE_HOST:localhost} #Catalogue Micro-Service
    port: ${CATALOGUE_PORT:8010}
customer:
  resource:
    host:  ${CUSTOMER_HOST:localhost} #Customers  Micro-Service
    port: ${CUSTOMER_PORT:8011}